name: Lark Notification

on:
  workflow_call:
    inputs:
      CHANNEL_ID:
        type: string
      NEW_VERSION:
        type: string
        default: "2.0.0"
      PREVIOUS_VERSION:
        type: string
        default: "1.0.0"
      VERSION_NAME:
        type: string
        default: "2.0.0"
      AUTHOR:
        type: string
        default: "github_user"
      TEAM:
        type: string
        default: "github_team"
      NEED_APPROVAL:
        type: boolean
        default: false
      JIRA_VERSION_ID:
        type: string
        default: "1.0.0"
      PROJECT_NAME:
        type: string
        default: "project name"
      USER_TITLE:
        type: string
        default: "Release Author"
      LARK_TITLE:
        type: string
        default: "Deployment"


jobs:
  escape-quotes:
    runs-on: ubuntu-latest

    steps:
      - name: Escape double quotes and format as one line
        id: parse_content
        run: |
          json_string='{
            "header": {
              "text_tag_list": [
                {
                  "tag": "text_tag",
                  "text": {
                    "tag": "plain_text",
                    "content": "title tag"
                  },
                  "color": "carmine"
                }
              ],
              "title": {
                "tag": "plain_text",
                "content": "main title"
              },
              "subtitle": {
                "tag": "plain_text",
                "content": "subtitle"
              },
              "template": "red"
            },
            "elements": [
              {
                "tag": "div",
                "text": {
                  "content": "Text content",
                  "tag": "plain_text"
                }
              }
            ]
          }'
          
          one_line_json=$(echo "$json_string" | tr -d '\n' | sed 's/"/\\"/g')
          echo "Escaped One-Line JSON: $one_line_json"
          echo "escaped_json=$one_line_json" >> $GITHUB_OUTPUT	
          echo ${{ secrets.LARK_APP_ID }}
      
      - name: get_tenant_ids
        id: get_tenant_id
        uses: fjogeleit/http-request-action@v1
        continue-on-error: true
        with:
          url: 'https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "app_id": "${{ secrets.LARK_APP_ID }}",
              "app_secret": "${{ secrets.LARK_APP_SECRET }}"
            }
      - name: deployment_message
        uses: fjogeleit/http-request-action@v1
        continue-on-error: true
        with:
          url: 'https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id'
          method: 'POST'
          bearerToken: ${{ fromJson(steps.get_tenant_id.outputs.response).tenant_access_token }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "receive_id": "oc_112c4bd19a5fb0fd1ded2dc1945445e3",
              "msg_type": "post",
              "content": "${{ steps.parse_content.outputs.escaped_json }}"
            }			

            