name: Escape Quotes and Send HTTP Request

on: [push]

jobs:
  escape-quotes-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step to define the JSON and escape double quotes
      - name: Escape double quotes and format as one line
        id: escape_quotes
        run: |
          json_string='{
            "en_us": {
              "title": "${{ inputs.SLACK_TITLE }} ${{ github.repository }}",
              "content": [
                [
                  {
                    "tag": "md",
                    "text": "**New Version: **${{ inputs.NEW_VERSION }}"
                  },
                  {
                    "tag": "md",
                    "text": "**Previous Version: **${{ inputs.PREVIOUS_VERSION }}"
                  },
                  {
                    "tag": "md",
                    "text": "**${{ inputs.USER_TITLE }}: **<${{ github.server_url }}/${{ inputs.AUTHOR }}|${{ inputs.AUTHOR }}>"
                  },
                  {
                    "tag": "md",
                    "text": "**Github Release:** ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ inputs.VERSION_NAME }}"
                  },
                  {
                    "tag": "md",
                    "text": "**Jira Release**: https://29022131.atlassian.net/projects/${{ inputs.PROJECT_NAME }}/versions/${{ inputs.JIRA_VERSION_ID }}"
                  },
                  {
                    "tag": "md",
                    "text": "**Status:** <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ job.status == 'success' && 'Success' || 'Failed' }}>"
                  }
                ]
              ]
            }
          }'
          
          # Remove newlines, replace spaces around key-value pairs and escape quotes
          one_line_json=$(echo "$json_string" | tr -d '\n' | sed 's/"/\\"/g')
          
          # Output the one-line escaped JSON to be used later
          echo "escaped_json=$one_line_json" >> $GITHUB_ENV

			- id: get_tenant_id
        uses: fjogeleit/http-request-action@v1
        continue-on-error: true
        with:
          url: 'https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "app_id": ${{secrets.LARK_APP_ID}},
              "app_secret": ${{secrets.LARK_APP_SECRET}}
            }

      # Step to send the HTTP request using the escaped one-line JSON string
      - name: deployment_message
        uses: fjogeleit/http-request-action@v1
        continue-on-error: true
        with:
          url: 'https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=${{ fromJson(steps.get_tenant_id.outputs.response).tenant_access_token }}'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "receive_id": "oc_112c4bd19a5fb0fd1ded2dc1945445e3",
              "msg_type": "post",
              "content": ${{ env.escaped_json }}}	
					
					
