name: Escape Quotes in Shell

on: [push]

jobs:
  escape-quotes:
    runs-on: ubuntu-latest

    steps:
      - name: Escape double quotes and format as one line
        run: |
          json_string='{
            "en_us": {
              "title": "${{ inputs.SLACK_TITLE }} ${{ github.repository }}",
              "content": [
                [
                  {
                    "tag": "md",
                    "text": "**New Version: **${{ inputs.NEW_VERSION }}"
                  },
                  {
                    "tag": "md",
                    "text": "**Previous Version: **${{ inputs.PREVIOUS_VERSION }}"
                  },
                  {
                    "tag": "md",
                    "text": "**${{ inputs.USER_TITLE }}: **<${{ github.server_url }}/${{ inputs.AUTHOR }}|${{ inputs.AUTHOR }}>"
                  },
                  {
                    "tag": "md",
                    "text": "**Github Release:** ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ inputs.VERSION_NAME }}"
                  },
                  {
                    "tag": "md",
                    "text": "**Jira Release**: https://29022131.atlassian.net/projects/${{ inputs.PROJECT_NAME }}/versions/${{ inputs.JIRA_VERSION_ID }}"
                  },
                  {
                    "tag": "md",
                    "text": "**Status:** <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ job.status == 'success' && 'Success' || 'Failed' }}>"
                  }
                ]
              ]
            }
          }'
          
          one_line_json=$(echo "$json_string" | tr -d '\n' | sed 's/"/\\"/g')
          echo "Escaped One-Line JSON: $one_line_json"

          # echo "escaped_json=$one_line_json" >> $GITHUB_ENV
