name: Escape Quotes in Shell

on: [push]

jobs:
  escape-quotes:
    runs-on: ubuntu-latest

    steps:
			- name: Get Tenant ID
				id: get_tenant_id
        uses: fjogeleit/http-request-action@v1
				
        continue-on-error: true
        with:
          url: 'https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "app_id": ${{secrets.LARK_APP_ID}},
              "app_secret": ${{secrets.LARK_APP_SECRET}}
            }
      - name: deployment_message
        uses: fjogeleit/http-request-action@v1
        continue-on-error: true
        with:
          url: 'https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=${{ fromJson(steps.get_tenant_id.outputs.response).tenant_access_token }}'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "receive_id": "oc_112c4bd19a5fb0fd1ded2dc1945445e3",
              "msg_type": "post",
              "content": ${{ env.escaped_json }}}	
					
					
