name: Escape Quotes in Shell

on: [push]

jobs:
  escape-quotes:
    runs-on: ubuntu-latest

    steps:
      - name: Escape double quotes and format as one line
        run: |
          json_string='{
            "en_us": {
              "title": "${{ inputs.SLACK_TITLE }} ${{ github.repository }}",
              "content": [
                [
                  {
                    "tag": "md",
                    "text": "**New Version: **${{ inputs.NEW_VERSION }}"
                  },
                  {
                    "tag": "md",
                    "text": "**Previous Version: **${{ inputs.PREVIOUS_VERSION }}"
                  },
                  {
                    "tag": "md",
                    "text": "**${{ inputs.USER_TITLE }}: **<${{ github.server_url }}/${{ inputs.AUTHOR }}|${{ inputs.AUTHOR }}>"
                  },
                  {
                    "tag": "md",
                    "text": "**Github Release:** ${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ inputs.VERSION_NAME }}"
                  },
                  {
                    "tag": "md",
                    "text": "**Jira Release**: https://29022131.atlassian.net/projects/${{ inputs.PROJECT_NAME }}/versions/${{ inputs.JIRA_VERSION_ID }}"
                  },
                  {
                    "tag": "md",
                    "text": "**Status:** <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ job.status == 'success' && 'Success' || 'Failed' }}>"
                  }
                ]
              ]
            }
          }'
          
          one_line_json=$(echo "$json_string" | tr -d '\n' | sed 's/"/\\"/g')
          echo "Escaped One-Line JSON: $one_line_json"
          echo "escaped_json=$one_line_json" >> $GITHUB_ENV	
          echo ${{ secrets.LARK_APP_ID }}
      
      - name: get_tenant_ids
        id: get_tenant_id
        uses: fjogeleit/http-request-action@v1
        continue-on-error: true
        with:
          url: 'https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "app_id": "${{ secrets.LARK_APP_ID }}",
              "app_secret": "${{ secrets.LARK_APP_SECRETS }}"
            }
      - name: output
        run: |
          echo ${{ fromJson(steps.get_tenant_id.outputs.response).tenant_access_token }}
      - name: deployment_message
        uses: fjogeleit/http-request-action@v1
        continue-on-error: true
        with:
          url: 'https://open.larksuite.com/open-apis/im/v1/messages?receive_id_type=chat_id'
          method: 'POST'
          bearerToken: ${{ fromJson(steps.get_tenant_id.outputs.response).tenant_access_token }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "receive_id": "oc_112c4bd19a5fb0fd1ded2dc1945445e3",
              "msg_type": "post",
              "content": "${{ env.escaped_json }}"
            }			

            