name: Escape Quotes in Shell

on: [push]

jobs:
  escape-quotes:
    runs-on: ubuntu-latest

    steps:
      - name: Escape double quotes using shell
        run: |
          json_string='{
						"key":{
							"hello":{
								"text":"test"
							\}
						\}
					\}'
          escaped_string=$(echo "$json_string" | sed 's/"/\\"/g')
          echo "Escaped String: $escaped_string"
